name: Check pull request source branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - edited
jobs:
  check-pr-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branches
        run: |
          if  [ ${{ github.base_ref }} == "production" ] ; then
            if  [ ${{startsWith(github.head_ref, 'feature')}} == "true" ] || [ ${{startsWith(github.head_ref, 'hotfix')}} == "true" ] ; then 
              echo "Merge requests are permitted as the source branch is from feature or hotfix branch"
            else 
              echo "Merge requests to production branch are forbidden as the PR only allowed to come from feature or hotfix branch."
              exit 1
            fi
          fi
