name: Deploy Service/Web App to Development

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of backend service/web app'
        required: true
        type: string
      published_port:
        required: true
        type: number
      target_port:
        required: false
        type: number
        default: 3300
      tsc_base_image:
        required: false
        type: string
        default: 'pinjammodal/typescript:3.9.10'
      node_base_image:
        required: false
        type: string
        default: 'pinjammodal/node:12.22.9-3.14'
      compose_file:
        required: true
        type: string
      docker_context:
        required: true
        type: string
      env_file:
        description: 'Use to load environment variable from file'
        required: false
        type: string
    secrets:
      cr_username:
        required: true
      cr_token:
        required: true
      signer_key:
        required: true
      dct_signer_priv_key:
        required: true
      signer_pass:
        required: true

env:
  NODE_ENV: development

jobs:

  build:
    runs-on: [self-hosted]

    outputs:
      imageTag: ${{ steps.meta.outputs.tags }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Meta
        id: meta
        run: echo "::set-output name=tags::pinjammodal/${{ inputs.service_name }}:${GITHUB_REF#refs/*/}" 

      # - name: Docker Meta
      #   id: meta
      #   uses: docker/metadata-action@v3
      #   with:
      #     images: pinjammodal/${{ inputs.service_name }}

      - run: echo "::notice title=docker meta::${{ steps.meta.outputs.tags }}"

      - name: Set Context Default
        run: docker context use default

      - name: Login to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.cr_username }} 
          password: ${{ secrets.cr_token }}

      - name: Load Environment Variable
        if: inputs.env_file != ''
        run: source ${{ inputs.env_file }}

      - name: Build Docker
        uses: docker/build-push-action@v2.10.0
        with:
          context: .
          outputs: type=docker
          tags: ${{ steps.meta.outputs.tags }}
          build-args: |
            TARGET_PORT=${{ inputs.target_port }}
            TSC_BASE=${{ inputs.tsc_base_image }}
            NODE_BASE=${{ inputs.node_base_image }}

        # run: |-
          # docker pull ${{ inputs.tsc_base_image }}
          # docker pull ${{ inputs.node_base_image }}
          # docker build --build-arg TARGET_PORT=${{ inputs.target_port }} --build-arg TSC_BASE=${{ inputs.tsc_base_image }} --build-arg NODE_BASE=${{ inputs.node_base_image }} -t ${{ steps.meta.outputs.tags }} -m 4g .

      - name: Check Build Result
        run: docker images | grep ${{ steps.meta.outputs.tags }}

      - name: Push Docker Image to Container Registry
        run: |-
          export DOCKER_CONTENT_TRUST=1
          cat <<EOT >> ${{secrets.signer_key}}
          ${{ secrets.dct_signer_priv_key }}
          EOT
          chmod 600 ${{secrets.signer_key}}
          export DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE=${{ secrets.signer_pass }}
          docker trust key load ${{ secrets.signer_key }}
          docker trust sign ${{ steps.meta.outputs.tags }}
          docker trust inspect --pretty ${{ steps.meta.outputs.tags }}

      - name: Logout from Container Registry
        run: |-
          docker logout
          rm ${{secrets.signer_key}}

  swarm-deploy:
    needs: build
    runs-on: [self-hosted]

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.cr_username }} 
          password: ${{ secrets.cr_token }}
      
      - name: Set Context
        run: docker context use ${{ inputs.docker_context }}

      - name: Check stack
        run: echo "STACK=$(docker stack ls | grep -c ${{ inputs.service_name }}[[:space:]])" >> $GITHUB_ENV

      - uses: actions/setup-node@v2
        if: env.STACK == 0
        with:
          node-version: '12'

      - run: npm install -g mustache
        if: env.STACK == 0

      - name: Set template variable
        if: env.STACK == 0
        run: |-
          cat<<EOT >> deployment/templates/config.json
          {
            "service_name": "${{ inputs.service_name }}",
            "image": "${{ needs.build.outputs.imageTag }}",
            "node_env": "${{ env.NODE_ENV }}",
            "target_port": "${{ inputs.target_port }}",
            "published_port": "${{ inputs.published_port }}"
          }
          EOT

      - name: Set Variable in Compose
        if: env.STACK == 0
        run: |- 
          rm ${{ inputs.compose_file }} || true
          mustache deployment/templates/config.json deployment/templates/dev-stack.mustache > ${{ inputs.compose_file }}

      - name: Stack deploy
        if: env.STACK == 0
        run: |-
          docker network create -d overlay --attachable public || true
          docker stack deploy --resolve-image=always --with-registry-auth --compose-file ${{ inputs.compose_file }} ${{ inputs.service_name }}

      - name: Update current service
        if: env.STACK == 1
        run: docker service update --health-retries 3 --health-interval 5s --with-registry-auth --image ${{ needs.build.outputs.imageTag }} ${{ inputs.service_name }}_${{ inputs.service_name }}

  runner-cleanup:
    needs: [swarm-deploy]
    runs-on: [self-hosted]

    steps:
      - name: Prune Images
        run: |-
          docker context use default
          docker image prune -a -f
          docker rmi -f $(docker images -f "dangling=true" -q) || true
          docker images
