name: Snyk

on:
  workflow_call:
    inputs:
      image_tag:
        required: false
        type: string
    secrets:
      snyk_token:
        required: true
      cr_username:
        required: true
      cr_token:
        required: true

jobs:
  code-scan:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@master

      - run: docker context use default

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
        with:
          args: --severity-threshold=high
          command: monitor

  container-scan:
    runs-on: [self-hosted]
    needs: code-scan

    steps:
      - run: docker context use default

      # - name: Set Dev Image Tag
      #   run: echo "image_tag=pinjammodal/${{ inputs.service_name }}:${GITHUB_REF#refs/*/}" >> "$GITHUB_ENV"

      - name: Load Image Tag
        id: loaded_image_tag
        uses: gradity/action-json-config@v1.0
        with:
          operation: 'get'
      
      - name: Debug Image Tag
        run: echo ${{ steps.loaded_image_tag.outputs.result }}1

      - name: Login to Container Registry
        run: |-
          docker context use default
          docker login -u ${{ secrets.cr_username }} -p ${{ secrets.cr_token }}

      - run: docker pull ${{ steps.loaded_image_tag.outputs.result }}

      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.snyk_token }}
        with:
          image: ${{ steps.loaded_image_tag.outputs.result }}
          args: --file=Dockerfile --severity-threshold=high
          command: monitor