name: testing

on:
  workflow_call:
    inputs:
      service_name:
        description: 'Name of backend service'
        required: true
        type: string
      published_port:
        required: true
        type: number
      target_port:
        required: true
        type: number
      # tsc_base_image:
      #   required: true
      #   type: string
      # node_base_image:
      #   required: true
      #   type: string
      compose_file:
        required: true
        type: string
    secrets:
      cr_username:
        required: true
      cr_token:
        required: true
      signer_key:
        required: true
      dct_signer_priv_key:
        required: true
      signer_pass:
        required: true
      snyk_token:
        required: true

env:
  DOCKER_IMAGE: pinjammodal/${{ inputs.service_name }}:${GITHUB_REF#refs/*/}
  DOCKER_IMAGE_DEV: pinjammodal/${{ inputs.service_name }}:${GITHUB_REF#refs/*//-prod/}
  DOCKER_IMAGE_DEV1: pinjammodal/${{ inputs.service_name }}:${GITHUB_REF#refs/*//-prod}
  DOCKER_IMAGE_DEV2: pinjammodal/${{ inputs.service_name }}:${GITHUB_REF#refs}
  DOCKER_IMAGE_DEV3: pinjammodal/${{ inputs.service_name }}:${GITHUB_REF#refs/}

jobs:

  set-dev-tag:
    runs-on: [self-hosted]
    steps:

    - uses: actions/checkout@v1

    - run: echo "${github_ref/}"
    - run: |

        ref="${github_ref////-}"
        echo $ref
        # echo "::set-env name=ref::$ref"
      env:
        github_ref: ${{ github.ref }}

    - name: Build and tag image
      run: echo " fameintel/booking:$ref"

      - run: echo ${{env.DOCKER_IMAGE}}
      - run: echo ${{env.DOCKER_IMAGE_DEV}}
      - run: echo ${{env.DOCKER_IMAGE_DEV1}}
      - run: echo ${{env.DOCKER_IMAGE_DEV2}}
      - run: echo ${{env.DOCKER_IMAGE_DEV3}}
      - run: echo ${GITHUB_REF#refs/*/-prod/-dev}

      - run: echo "DOCKER_IMAGE_DEVEL=${{env.DOCKER_IMAGE//-prod/}}"-dev >> $GITHUB_ENV
      - run: echo "DOCKER_IMAGE_DEVEL1=${{$DOCKER_IMAGE//-prod/}}"-dev >> $GITHUB_ENV